/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tenebrius (https://sketchfab.com/Tenebrius)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-piece-knight-horse-dd5c780cce3d46e4b34606e659f437e0
Title: Chess Piece: Knight (Horse)
*/

import { useGSAP } from '@gsap/react';
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap';
import { useRef } from 'react';

const Chess = (props) => {
  const { nodes, materials } = useGLTF('/portfolio/models/chess_piece_knight_horse.glb');
  const chessRef = useRef();

  useGSAP(() => {
    gsap.to(chessRef.current.rotation, {
      y: "+=6.28",
      duration: 5,
      repeat: -1,
      ease: "linear",
      onUpdate: () => {
        chessRef.current.rotation.y %= (2 * Math.PI);
      }
    });
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Horse_HorseTex_0.geometry}
        material={materials.HorseTex}
        rotation={[0.5, 0, 0]}
        ref={chessRef}
      />
      <directionalLight position={[0, 5, 5]} intensity={1.5} />
    </group>
  )
}

useGLTF.preload('/portfolio/models/chess_piece_knight_horse.glb');

export default Chess;
