/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: KateGirl.SK (https://sketchfab.com/KateGirl.SK)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-4a7eda032c7740959c6f7adbaee29883
Title: Coffee
*/

import { useGSAP } from '@gsap/react';
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap';
import { useRef } from 'react'

const Coffee = (props) => {
  const { nodes, materials } = useGLTF('models/coffee.glb')
  const coffeeRef = useRef();

  useGSAP(() => {
    gsap.to(coffeeRef.current.rotation, {
      y: "+=6.28",
      // x: "+=62.8",
      duration: 5,
      repeat: -1,
      ease: "linear",
      onUpdate: () => {
      coffeeRef.current.rotation.y %= (2 * Math.PI);
      },
    });
  });

  return (
    <group {...props} dispose={null} ref={coffeeRef}>
      <group scale={0.01}>
        <mesh
          geometry={nodes['Coffee001_Materi��l053_0'].geometry}
          material={materials['Materil.053']}
          // position={[123.524, 193.538, 2498.634]}
          rotation={[-Math.PI / 2, 0.5, 0]}
          scale={51.938}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/coffee.glb')

export default Coffee;