/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SketchyBot (https://sketchfab.com/SketchyB0t_3D_Fabrication)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/old-computer-v2-b389fddc31ea459597fb3e1d23dcb545
Title: Old Computer V2
*/
import { useGSAP } from '@gsap/react';
import { useGLTF, useVideoTexture } from '@react-three/drei'
import gsap from 'gsap';
import PropTypes from 'prop-types';
import { useRef } from 'react';

const DemoComputer = (props) => {
  const { nodes, materials } = useGLTF('models/old_computer_v2.glb');
  const txtr = useVideoTexture(props.texture);
  const groupRef = useRef();

  useGSAP(() => {
    gsap.from(groupRef.current.rotation, {
      z: Math.PI,
      duration: 1,
      ease: 'power3.out',
    });
  }, [txtr]);

  return (
    <group dispose={null} ref={groupRef}>
      <group name="Sketchfab_model">
        <group>
          <group name="Computer1" >
            <mesh
              name="Computer1_Computer001_0"
              geometry={nodes.Computer1_Computer001_0.geometry}
              material={materials['Computer.001']}
            />
            <mesh
              name="Computer1_Screen001_0"
              geometry={nodes.Computer1_Screen001_0.geometry}
              material={materials['Screen.001']}
            >
              <meshBasicMaterial map={txtr} />
            </mesh>
          </group>
        </group>
      </group>
    </group>
  )
}
DemoComputer.propTypes = {
  texture: PropTypes.string.isRequired,
};

useGLTF.preload('models/old_computer_v2.glb');
useGLTF.preload('models/old_computer_v2.glb');

export default DemoComputer;
